FROM node:18

WORKDIR /app

# Copy package & install
COPY package*.json ./
RUN npm install

# Copy toàn bộ source
COPY . .

# Cài ts-node-dev nếu chưa có
RUN npm install -g ts-node-dev

# Dev mode: hot reload khi code thay đổi
CMD ["npm", "run", "dev"]
